/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Paolo
 */
public class LogIn extends javax.swing.JFrame
{

    /**
     * Creates new form GUI
     */
    public LogIn()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        layer = new javax.swing.JLayeredPane();
        Home = new javax.swing.JPanel();
        cfL = new javax.swing.JLabel();
        codiceFiscaleF = new javax.swing.JTextField();
        passwordL = new javax.swing.JLabel();
        passwordF = new javax.swing.JPasswordField();
        annulla = new javax.swing.JButton();
        accedi = new javax.swing.JButton();
        registrati = new javax.swing.JButton();
        lista = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        cfL.setText("codice fiscale");
        cfL.setMinimumSize(new java.awt.Dimension(60, 20));

        codiceFiscaleF.setMinimumSize(new java.awt.Dimension(60, 25));
        codiceFiscaleF.setPreferredSize(new java.awt.Dimension(120, 25));

        passwordL.setText("password");
        passwordL.setMaximumSize(new java.awt.Dimension(60, 20));
        passwordL.setMinimumSize(new java.awt.Dimension(60, 20));
        passwordL.setPreferredSize(new java.awt.Dimension(60, 20));

        passwordF.setText("jPasswordField1");
        passwordF.setMinimumSize(new java.awt.Dimension(60, 25));
        passwordF.setPreferredSize(new java.awt.Dimension(120, 25));

        annulla.setText("Annulla");
        annulla.addActionListener(formListener);

        accedi.setText("Accedi");
        accedi.addActionListener(formListener);

        registrati.setText("Registrati");

        lista.setText("Lista Centri");
        lista.addActionListener(formListener);

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(cfL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(annulla, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordF, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(codiceFiscaleF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accedi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cfL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codiceFiscaleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulla)
                    .addComponent(accedi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista)
                    .addComponent(registrati))
                .addGap(192, 192, 192))
        );

        passwordF.getAccessibleContext().setAccessibleDescription("");
        annulla.getAccessibleContext().setAccessibleName("annulla");

        layer.setLayer(Home, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout layerLayout = new javax.swing.GroupLayout(layer);
        layer.setLayout(layerLayout);
        layerLayout.setHorizontalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layerLayout.setVerticalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Home.getAccessibleContext().setAccessibleName("Home");
        Home.getAccessibleContext().setAccessibleDescription("");
        Home.getAccessibleContext().setAccessibleParent(Home);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(layer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(layer)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layer.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Frame");

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener
    {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            if (evt.getSource() == annulla)
            {
                LogIn.this.annullaActionPerformed(evt);
            }
            else if (evt.getSource() == accedi)
            {
                LogIn.this.accediActionPerformed(evt);
            }
            else if (evt.getSource() == lista)
            {
                LogIn.this.listaActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void annullaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_annullaActionPerformed
    {//GEN-HEADEREND:event_annullaActionPerformed
        codiceFiscaleF.setText(null);
        passwordF.setText(null);
    }//GEN-LAST:event_annullaActionPerformed

    private void accediActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_accediActionPerformed
    {//GEN-HEADEREND:event_accediActionPerformed
        if(true) // modificare dopo
        {
            Home.setVisible(false);
        }
        else
        {
            
        }
    }//GEN-LAST:event_accediActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_listaActionPerformed
    {//GEN-HEADEREND:event_listaActionPerformed
        InfoCentri ic = new InfoCentri();
        this.setSize(ic.getWidth(),ic.getHeight());
        ic.setVisible(true);
    }//GEN-LAST:event_listaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JButton accedi;
    private javax.swing.JButton annulla;
    private javax.swing.JLabel cfL;
    private javax.swing.JTextField codiceFiscaleF;
    private javax.swing.JLayeredPane layer;
    private javax.swing.JButton lista;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JLabel passwordL;
    private javax.swing.JButton registrati;
    // End of variables declaration//GEN-END:variables
}
